builds:
  -
    id: build
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    ldflags:
      - -s -w -X main.Version="{{ .Version }}" -X main.SHA="{{ .FullCommit }}" -X main.BuildTime={{ .Timestamp }}
before:
  hooks:
  - go mod tidy
changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore'
    - Merge pull request
    - Merge branch
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
universal_binaries:
  -
    replace: true
    id: build

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    id: packages
    homepage:  https://stackexchange.github.io/dnscontrol/
    description: "DNSControl: Infrastructure as Code for DNS Zones"
    maintainer: 'Tom Limoncelli <tlimoncelli@stackoverflow.com>'
    license: MIT
    formats:
    - deb
    - rpm
dockers:
  - image_templates:
    - &amd_image "stackexchange/{{.ProjectName}}:{{ .Version }}-amd64"
    goos: linux
    goarch: amd64
    use: buildx
    ids:
    - build
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{ .Date }}"
    - "--label=org.opencontainers.image.name={{ .ProjectName }}"
    - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    - "--label=org.opencontainers.image.version={{ .Version }}"
    - "--label=org.opencontainers.image.source={{ .GitURL }}"
    - "--platform=linux/amd64"
  - image_templates:
    - &arm_image "stackexchange/{{.ProjectName}}:{{ .Version }}-arm64"
    goos: linux
    goarch: arm64
    use: buildx
    ids:
    - build
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{ .Date }}"
    - "--label=org.opencontainers.image.name={{ .ProjectName }}"
    - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    - "--label=org.opencontainers.image.version={{ .Version }}"
    - "--label=org.opencontainers.image.source={{ .GitURL }}"
    - "--platform=linux/arm64"
docker_manifests:
  - name_template: "stackexchange/{{.ProjectName}}:{{ .Version }}"
    image_templates:
      - *amd_image
      - *arm_image
  - name_template: "stackexchange/{{.ProjectName}}:latest"
    image_templates:
      - *amd_image
      - *arm_image
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
announce:
  # Skip the announcing feature in some conditions, for instance, when publishing patch releases.
  # Valid options are `true`, `false`, empty, or a template that evaluates to a boolean (`true` or `false`).
  # Defaults to empty (which means false).
  skip: true
